### ISSUE TITLE
Any resources on custom animator for arm movement

### ISSUE THREAD

**Issue by serifpersia** [adeleine1412/leapmotion-osc#11]
I'm working on MPU6050 tracking for arms currently I'm trying the OSC parameters via TouchOSC to emulate the input that will be eventually be from ESP32 MPU6050 data(arm, elbow and hip). 

I was able import and use the fingers one this repo provided but I'm not able to create my own. I tried to create animations for arm movement but nothing changes when i move the float sliders. 

Could you provide resources like video tutorial or some guidance on how to create similar thing but for arms not fingers. The arms have front back, up down and left right in animator. EDIT: Thanks anyways I might give up on this idea for now.
Thanks

**Comment by philippgitpush** [comment]
Hello Serif! Sorry for the late reply.

the animations provided in this repo were created by me by hand, so unfortunately I can't link you a tutorial or guide.

IIRC I used the [muscle animation editor](https://assetstore.unity.com/packages/tools/animation/muscle-animation-editor-32233) to create them as it made things a little easier.

I created a series of animations for all the fingers. Each finger had at least two animations where it was fully extended in one and fully retracted in the other. The blending tree shown in the [readme](https://github.com/ThatGuyThimo/leapmotion-osc/blob/master/README.md) has the exact layout you need.

Another note / my suggestion: i heard VRChat added full FBT via OSC parameters / [OSC tracker](https://docs.vrchat.com/docs/osc-trackers), which might be the way to go.

I hope this helps you in some way!

**Comment by serifpersia** [comment]
Thanks for the reply. I had the idea to do some arm tracking via cheap mpu6050 but in desktop mode not in vr. But I gave up on the idea since I was not able to figure out why my animations where not playing on runtime(even tho it works without any masks on the layers).

Thanks again!
