### ISSUE TITLE
Why is it so hard to do?

### ISSUE THREAD

**Issue by lawlerboy1** [adeleine1412/leapmotion-osc#4]
could you leave a tutorial, currently the app itself is working I just can't get my vrc model to do what it's supposed to, otherwise the program might not be accessing my camera pls help!

**Comment by philippgitpush** [comment]
Hey @lawlerboy1, I would like to ask you for additional information on this.
(How is your Avatar Setup, what Versions of **everything**, including Unity, NodeJS, Leap SDK etc. are you using, do your other animations work)

It's very difficult to make out problems in Unity if you don't have a clear picture of how it is setup.
There is an example animation controller in the repo, you can find it here:
https://github.com/adeleine1412/leapmotion-osc/tree/master/animations

Make sure you are not running into write defaults issues.
For testing, you can use lyuma's Av3Emulator, as it supports OSC debugging inside Unity and adds additional gizmos.
https://github.com/lyuma/Av3Emulator
