### ISSUE TITLE
windows defender detected a trojan

### ISSUE THREAD

**Issue by mekajuju** [adeleine1412/leapmotion-osc#7]
when running the 1.0.3 windows exe, defender warned me of a severe trojan threat. 
virustotal says the same: https://www.virustotal.com/gui/file/4c7959375e5229106a02383aca38f811456ce0d27c3a4b9a737ab065a47292a2

what's up with that? :)

**Comment by mekajuju** [comment]
lol, I'm sure this is it - https://github.com/SerGreen/Appacker

**Comment by philippgitpush** [comment]
Yes, this is due to Apppacker. To avoid this, download the unpacked Windows version:
https://github.com/adeleine1412/leapmotion-osc/releases/download/release-1.0.3/leapmotionosc-1.0.3-windows.zip

**Comment by ThatGuyThimo** [comment]
@loremgetsum We included an installer in the newest [release](https://github.com/adeleine1412/leapmotion-osc/releases/tag/release-1.1.0), this should no longer trigger your antivirus/Windows defender.
